language: c

matrix:
  include:
    - compiler: gcc
      os: osx
      env:
        - DISTRO=osx
        - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig
    - compiler: clang
      os: osx
      env:
        - DISTRO=osx
        - PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

compiler:
  - clang
  - gcc

os: linux
sudo: required
services: docker
env:
  matrix:
    - DISTRO=fedora:rawhide
    - DISTRO=fedora:latest
    - DISTRO=centos:latest
    - DISTRO=debian:unstable
    - DISTRO=debian:testing
    - DISTRO=ubuntu:devel
    - DISTRO=ubuntu:latest

before_install:
  - >
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker create --name=jose -t -v `pwd`:/tmp/build -w /tmp/build $DISTRO /bin/cat
      docker start jose
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then DOCKER="docker exec jose"; fi
  - $DOCKER /usr/bin/env CC=$CC DISTRO=$DISTRO ./.travis.install

script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then DOCKER="docker exec jose"; fi
  - $DOCKER /usr/bin/env CC=$CC ./.travis.script

after_script:
  - >
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      docker kill jose
      docker rm jose
    fi
