sudo: required

language: c

services:
  - docker

#osx_image: xcode8
#os:
#  - linux
#  - osx

compiler:
  - clang
  - gcc

env:
  - DISTRO=debian:jessie
  - DISTRO=ubuntu:xenial
  - DISTRO=ubuntu:wily
  - DISTRO=ubuntu:vivid
  - DISTRO=fedora:latest
  - DISTRO=fedora:24
  - DISTRO=fedora:23

script:
  - >
    docker run
    -v `pwd`:/tmp/build
    -w /tmp/build
    -e CC=$CC
    $DISTRO /bin/bash -ex .travis.test $DISTRO
